export const AuthErrors = {
  AUTH_CANCELED: 'ERR_AUTH_CANCELED',
  EMAIL_REQUIRED: 'ERR_EMAIL_REQUIRED',
  PROVIDER_FAILURE: 'ERR_PROVIDER_FAILURE',
  ACCOUNT_EXISTS: 'ERR_ACCOUNT_EXISTS',
  INTERNAL_STABILITY: 'ERR_INTERNAL_STABILITY',
};
